CREATE TABLE IF NOT EXISTS generation_job (
    id VARCHAR(36) PRIMARY KEY, prompt CLOB NOT NULL, status VARCHAR(24) NOT NULL,
    current_stage VARCHAR(64) NOT NULL, message VARCHAR(1000), original_image_path VARCHAR(1000),
    clothing_image_path VARCHAR(1000), final_image_path VARCHAR(1000), reply CLOB,
    error_message CLOB, error_details CLOB, snapshot_json CLOB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_generation_job_created_at ON generation_job(created_at);
CREATE INDEX IF NOT EXISTS idx_generation_job_status_updated ON generation_job(status, updated_at);

CREATE TABLE IF NOT EXISTS generation_step_event (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, job_id VARCHAR(36) NOT NULL,
    event_type VARCHAR(40) NOT NULL, stage VARCHAR(64) NOT NULL, message VARCHAR(1000) NOT NULL,
    result_json CLOB, created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_step_event_job FOREIGN KEY(job_id) REFERENCES generation_job(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_step_event_job_id_id ON generation_step_event(job_id, id);

CREATE TABLE IF NOT EXISTS portrait_attempt (
    job_id VARCHAR(36) NOT NULL, attempt_number INT NOT NULL, image_path VARCHAR(1000) NOT NULL,
    generation_prompt CLOB NOT NULL, quality_report_json CLOB NOT NULL, selected BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY(job_id, attempt_number),
    CONSTRAINT fk_portrait_attempt_job FOREIGN KEY(job_id) REFERENCES generation_job(id) ON DELETE CASCADE
);
CREATE TABLE IF NOT EXISTS outfit_attempt (
    job_id VARCHAR(36) NOT NULL, attempt_number INT NOT NULL, image_path VARCHAR(1000) NOT NULL,
    replacement_prompt CLOB NOT NULL, quality_report_json CLOB NOT NULL, selected BOOLEAN DEFAULT FALSE NOT NULL,
    created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY(job_id, attempt_number),
    CONSTRAINT fk_outfit_attempt_job FOREIGN KEY(job_id) REFERENCES generation_job(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS clothing_profile (
    id VARCHAR(64) PRIMARY KEY, file_name VARCHAR(255) NOT NULL, image_path VARCHAR(1000) NOT NULL,
    sha256 VARCHAR(64) NOT NULL UNIQUE, profile_json CLOB NOT NULL, search_text CLOB NOT NULL,
    model_name VARCHAR(100) NOT NULL, updated_at TIMESTAMP(6) NOT NULL
);
CREATE TABLE IF NOT EXISTS fashion_learned_experience (
    id VARCHAR(36) PRIMARY KEY, source_job_id VARCHAR(36) NOT NULL UNIQUE, title VARCHAR(255) NOT NULL,
    scenario CLOB NOT NULL, experience_json CLOB NOT NULL, knowledge_text CLOB NOT NULL,
    quality_score INT NOT NULL, approved BOOLEAN DEFAULT TRUE NOT NULL, created_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_fashion_experience_job FOREIGN KEY(source_job_id) REFERENCES generation_job(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS video_generation_job (
    id VARCHAR(36) PRIMARY KEY, source_job_id VARCHAR(36) NOT NULL, status VARCHAR(32) NOT NULL,
    message VARCHAR(1000), source_video_path VARCHAR(1000), final_video_path VARCHAR(1000),
    quality_score INT, quality_report_json CLOB, error_message CLOB, snapshot_json CLOB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_video_generation_source_job FOREIGN KEY(source_job_id) REFERENCES generation_job(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_video_generation_source ON video_generation_job(source_job_id, created_at);

CREATE TABLE IF NOT EXISTS asset_selection_usage (
    asset_type VARCHAR(20) NOT NULL, asset_key VARCHAR(255) NOT NULL, display_name VARCHAR(255) NOT NULL,
    use_count BIGINT DEFAULT 0 NOT NULL, last_used_at TIMESTAMP(6) NOT NULL,
    PRIMARY KEY(asset_type, asset_key)
);
CREATE TABLE IF NOT EXISTS comfyui_video_generation_job (
    id VARCHAR(36) PRIMARY KEY, account_id VARCHAR(36), prompt CLOB NOT NULL, duration_seconds INT NOT NULL,
    resolution VARCHAR(32) NOT NULL, image_count INT NOT NULL, status VARCHAR(24) NOT NULL,
    message VARCHAR(1000), remote_task_id VARCHAR(128), remote_result_url CLOB,
    final_video_path VARCHAR(1000), error_message CLOB, snapshot_json CLOB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL
);
ALTER TABLE comfyui_video_generation_job ADD COLUMN IF NOT EXISTS account_id VARCHAR(36);
CREATE INDEX IF NOT EXISTS idx_comfyui_video_account_created ON comfyui_video_generation_job(account_id, created_at);
CREATE TABLE IF NOT EXISTS qwen_video_script_job (
    id VARCHAR(36) PRIMARY KEY, source_address CLOB NOT NULL, source_file_name VARCHAR(255),
    video_path VARCHAR(1000), status VARCHAR(24) NOT NULL, message VARCHAR(1000), script_text CLOB,
    error_message CLOB, created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS app_account (
    id VARCHAR(36) PRIMARY KEY, username VARCHAR(80) NOT NULL UNIQUE, password_hash VARCHAR(100) NOT NULL,
    administrator BOOLEAN DEFAULT FALSE NOT NULL, enabled BOOLEAN DEFAULT TRUE NOT NULL,
    expires_at TIMESTAMP(6), allowed_menus CLOB NOT NULL, created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL
);
CREATE TABLE IF NOT EXISTS app_account_setting (
    account_id VARCHAR(36) PRIMARY KEY, runninghub_key CLOB, snapany_key CLOB, qwen_key CLOB,
    zhipu_key CLOB, comfyui_token CLOB, clothing_directory VARCHAR(1000), video_directory VARCHAR(1000),
    generated_directory VARCHAR(1000), video_export_directory VARCHAR(1000),
    audit_output_directory VARCHAR(1000), story_output_directory VARCHAR(1000),
    bgm_directory VARCHAR(1000), qwen_output_directory VARCHAR(1000), updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_account_setting_account FOREIGN KEY(account_id) REFERENCES app_account(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS short_drama_director_job (
    id VARCHAR(36) PRIMARY KEY, mode VARCHAR(40) NOT NULL, source_type VARCHAR(16) NOT NULL,
    source_file_name VARCHAR(255), source_text CLOB, action_tier VARCHAR(8), platform VARCHAR(32),
    aspect_ratio VARCHAR(16), status VARCHAR(24) NOT NULL, message VARCHAR(1000), result_text CLOB,
    error_message CLOB, created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_short_drama_director_created ON short_drama_director_job(created_at);

CREATE TABLE IF NOT EXISTS my_script_project (
    id VARCHAR(36) PRIMARY KEY, source_job_id VARCHAR(36) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL, settings_text CLOB NOT NULL,
    created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL
);
CREATE TABLE IF NOT EXISTS my_script_episode (
    id VARCHAR(36) PRIMARY KEY, project_id VARCHAR(36) NOT NULL, episode_number INT NOT NULL,
    title VARCHAR(255) NOT NULL, content CLOB, status VARCHAR(24) NOT NULL,
    message VARCHAR(1000), error_message CLOB, created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_my_script_episode_project FOREIGN KEY(project_id) REFERENCES my_script_project(id) ON DELETE CASCADE,
    CONSTRAINT uq_my_script_episode_number UNIQUE(project_id, episode_number)
);
CREATE INDEX IF NOT EXISTS idx_my_script_episode_project ON my_script_episode(project_id, episode_number);

CREATE TABLE IF NOT EXISTS script_replication_segment (
    id VARCHAR(36) PRIMARY KEY, episode_id VARCHAR(36) NOT NULL, segment_number INT NOT NULL,
    content CLOB NOT NULL, duration_seconds INT NOT NULL, status VARCHAR(24) NOT NULL,
    comfy_task_id VARCHAR(36), error_message CLOB, created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_script_replication_episode FOREIGN KEY(episode_id) REFERENCES my_script_episode(id) ON DELETE CASCADE,
    CONSTRAINT uq_script_replication_segment UNIQUE(episode_id, segment_number)
);
CREATE INDEX IF NOT EXISTS idx_script_replication_episode ON script_replication_segment(episode_id, segment_number);
ALTER TABLE script_replication_segment ADD COLUMN IF NOT EXISTS character_names_json CLOB;
ALTER TABLE script_replication_segment ADD COLUMN IF NOT EXISTS handoff_text CLOB;
CREATE TABLE IF NOT EXISTS my_script_character_asset (
    id VARCHAR(36) PRIMARY KEY, project_id VARCHAR(36) NOT NULL, character_name VARCHAR(120) NOT NULL,
    role_level VARCHAR(24), anchor_text VARCHAR(255), image_sources_json CLOB, sort_order INT NOT NULL,
    created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_my_script_character_project FOREIGN KEY(project_id) REFERENCES my_script_project(id) ON DELETE CASCADE,
    CONSTRAINT uq_my_script_character_name UNIQUE(project_id, character_name)
);
CREATE INDEX IF NOT EXISTS idx_my_script_character_project ON my_script_character_asset(project_id, sort_order);
CREATE TABLE IF NOT EXISTS script_replication_generation (
    id VARCHAR(36) PRIMARY KEY, segment_id VARCHAR(36) NOT NULL, comfy_task_id VARCHAR(36), status VARCHAR(24) NOT NULL,
    final_video_url CLOB, error_message CLOB, created_at TIMESTAMP(6) NOT NULL, updated_at TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_script_replication_generation_segment FOREIGN KEY(segment_id) REFERENCES script_replication_segment(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_script_replication_generation_segment ON script_replication_generation(segment_id, created_at);
