# Stock Lens public information edition configuration.
# Restart the application after changing this file.

# Encrypted external data channel expiry date. Replace the whole ciphertext when renewing access.
stock.license.monitor-expiry-ciphertext=v2.iRYNWOeR53sXo4cKqRNscoWxcfuND_3MLbzlNVSph-93bO7ZrT-E_Pu6AcPthQ.5ZlilfvkSS3b-FlSlpLKF0LF83mo0NZ_3SCEHkV0uDdWQQKZM43hMAuEHP4y65g9IT_OhcivxH0_DdHbUTwDAQ
