package dev.learning.fashionagent.pipeline;

public enum PipelineStage {
    ACCEPTED,
    AI_ENRICHING_PORTRAIT_PROMPT,
    AGENT1_GENERATING_PERSON,
    AI_VERIFYING_PORTRAIT,
    AI_REFINING_PORTRAIT_PROMPT,
    AGENT2_SELECTING_CLOTHING,
    AI_ANALYZING_CLOTHING,
    RAG_RETRIEVING_FASHION_KNOWLEDGE,
    AGENT3_REPLACING_OUTFIT,
    AI_VERIFYING_OUTFIT,
    AI_REFINING_PROMPT,
    AGENT4_PRESENTING_RESULT,
    RAG_LEARNING_EXPERIENCE,
    COMPLETED,
    CANCELLED,
    FAILED
}
